syllabin/blueprints/main.py
import os
from datetime import date, timedelta
from flask import render_template, flash, redirect, url_for, current_app, send_from_directory, request, abort, Blueprint, make_response
from flask_login import login_required, current_user
from sqlalchemy import or_

from syllabin.utils import getDayEntries, getCurrentWeek, getFirstWeekDay, getMondayForWeek, getWeekEntries
from syllabin.models import Announcement
from syllabin.components import db

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    delta = request.args.get('delta', '0')
    if current_user.is_authenticated:
        today = date.today() + timedelta(days=int(delta))
        if current_user.group:
            announcements = Announcement.query.filter(or_(Announcement.group_id == current_user.group.id, Announcement.group_id == None)).all()
        else:
            announcements = Announcement.query.all()
        if announcements:
            for announcement in announcements:
                if announcement.expires.date() <= date.today():
                    db.session.delete(announcement)
                    db.session.commit()
        return render_template('main/index.html', announcements=announcements, entries=getDayEntries(today), week=getCurrentWeek(today), delta=int(delta))
    else:
        return render_template('main/index.html')


@main_bp.route('/week/<int:week_num>')
@login_required
def week(week_num):
    first_day = getMondayForWeek(week_num-1)
    range_string = first_day.strftime("%d/%m/%Y") + " to " + (first_day+timedelta(days=4)).strftime("%d/%m/%Y")
    colors = ["#C1A3A3", "#3F6DBD", "#43A126", "#B9BA30", "#B2508B"]
    return render_template('main/week.html', entries=getWeekEntries(week_num), week=week_num, colors=colors, range_string=range_string)


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/sw.js')
def service_worker():
    response = make_response(send_from_directory('static', 'sw.js'))
    response.headers['Cache-Control'] = 'no-cache'
    return response


@main_bp.route('/manifest.json')
def manifest():
    return send_from_directory('static', 'manifest.json')


@main_bp.route('/favicon.ico')
def favicon():
    return send_from_directory('static', 'favicon.ico')


@main_bp.route('/robots.txt')
def robots():
    return send_from_directory('static', 'robots.txt')

syllabin/templates/main/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
	<div class="page-header" style="padding-top:0">
        <h1 class="bd-title" id="content">Home</h1>
	</div>
	<div class="row">
		<div class="col-sm-8">
{% if not current_user.is_authenticated %}
<h2>Authenticate to see the timetable.</h2>
{% endif %}
{% if announcements %}
<h3>Announcements:
{% for announcement in announcements %}
<div aria-label="Announcement {{ loop.index }} {{ announcement.message }}" style="all:unset;">{{ announcement.message }}</div>{% if not loop.last %} | {% endif %}
{% endfor %}
</h3>
{% endif %}
{% if entries %}
<h4>Timetable for {{ entries[0][0].weekday }}, week {{ week }}</h4>
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Time</th>
      <th scope="col">Subject</th>
      <th scope="col">Room</th>
      <th scope="col">Professor</th>
    </tr>
  </thead>
<tbody>
{% for entry in entries %}
<tr>
<th scope="row">{% if entry[1] == 1 %}9:00-10:20{% elif entry[1] == 2 %}10:30-11:50{% elif entry[1] == 3 %}12:40-14:00{% elif entry[1] == 4 %}14:10-15:30{% else %}15:40-17:00{% endif %}</th>
<td>{{ entry[0].subject.name }}</td>
<td>{{ entry[0].room.name }}</td>
<td>{{ entry[0].professor.name }}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
{% elif current_user.is_authenticated %}
<h4>No lessons {% if delta == 0 %}today{% else %}this day{% endif %}.</h4>
{% endif %}
</div>
{% if current_user.is_authenticated %}
{% if delta == 0 %}<a href="{{ url_for('main.index', delta=1) }}" class="mb-2">Lessons tomorrow</a>{% else %}
<a href="{{ url_for('main.index') }}" class="mb-2">Lessons today</a>
<a href="{{ url_for('main.index', delta=delta+1) }}" class="mb-2">Next day</a>{% endif %}
<a href="{{ url_for('main.week', week_num=week) }}" class="mb-2">Week view</a>
{% endif %}
</div>
</div>
{% endblock %}

syllabin/templates/main/week.html
{% extends 'base.html' %}
{% block title %}Week view{% endblock %}
{% block content %}
<a id="skippy_week" style="position:absolute;width:1px;height:1px;padding:0;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0;" href="#week_selector">
  <div class="container">
    <span class="skiplink-text">Skip to week selector</span>
  </div>
</a>
	<div class="page-header" style="padding-top:0">
        <h1 class="bd-title" id="content">Week view</h1>
	</div>
	<div class="row">
		<div class="col-sm-10">
<h4>Timetable for week {{ week }}. {{ range_string }}</h4>
<h5>{{ day }}</h5>
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Day</th>
      <th scope="col">Time</th>
      <th scope="col">Subject</th>
      <th scope="col">Room</th>
      <th scope="col">Professor</th>
    </tr>
  </thead>
<tbody>
{% for day in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'] %}
{% set outer_loop = loop %}
{% for entry in entries[loop.index0] %}
<tr {% if loop.last %}style="border-bottom:1px;"{% endif %}>
{% if loop.first %}<th rowspan="{{ loop.length }}" style="background-color: {{ colors[outer_loop.index0] }} !important;"><p style="writing-mode: vertical-rl; margin:0px;">{{ day }}</p></th>{% endif %}
<td scope="row">{% if entry[1] == 1 %}9:00-10:20{% elif entry[1] == 2 %}10:30-11:50{% elif entry[1] == 3 %}12:40-14:00{% elif entry[1] == 4 %}14:10-15:30{% else %}15:40-17:00{% endif %}</td>
<td>{{ entry[0].subject.name }}</td>
<td>{{ entry[0].room.name }}</td>
<td>{{ entry[0].professor.name }}</td>
</tr>
{% endfor %}
{% endfor %}
</tbody>
</table>
</div>
<nav aria-label="Week selector" id="week_selector">
  <ul class="pagination">
    <li class="page-item {% if week == 1 %}disabled{% endif %}">
      <a class="page-link" href="{{ url_for('main.week', week_num=week-1) }}" tabindex="-1">Previous</a>
    </li>
{% for page in range(week-3 if week > 3 else 1,week) %}
    <li class="page-item"><a class="page-link" href="{{ url_for('main.week', week_num=page) }}">{{ page }}</a></li>
{% endfor %}
    <li class="page-item active">
      <a class="page-link" href="#">{{ week }}</a>
    </li>
{% for page in range(week+1, week+4 if week <16 else 20) %}
    <li class="page-item"><a class="page-link" href="{{ url_for('main.week', week_num=page) }}">{{ page }}</a></li>
{% endfor %}
    <li class="page-item" {% if week == 19 %}disabled{% endif %}>
      <a class="page-link" href="{{ url_for('main.week', week_num=week+1) }}">Next</a>
    </li>
  </ul>
</nav>
</div>
</div>
</div>
{% endblock %}