syllaboard/blueprints/auth.py
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login

from syllaboard.components import db
from syllaboard.forms.auth import LoginForm
from syllaboard.models import User
from syllaboard.utils import redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('Login success.', 'info')
                return redirect_back()
            else:
                flash('Your account is blocked.', 'warning')
                return redirect(url_for('main.index'))
        flash('Invalid email or password.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data.lower()
        username = form.username.data
        password = form.password.data
        user = User(name=name, email=email, username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        flash('Confirm email sent, check your inbox.', 'info')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)


@auth_bp.route('/forget-password', methods=['GET', 'POST'])
def forget_password():
    return redirect(url_for('main.index'))
#    if current_user.is_authenticated:
#        return redirect(url_for('main.index'))

#    form = ForgetPasswordForm()
#    if form.validate_on_submit():
#        user = User.query.filter_by(email=form.email.data.lower()).first()
#        if user:
#            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
#            send_reset_password_email(user=user, token=token)
#            flash('Password reset email sent, check your inbox.', 'info')
#            return redirect(url_for('.login'))
#        flash('Invalid email.', 'warning')
#        return redirect(url_for('.forget_password'))
#    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('main.index'))

syllaboard/blueprints/main.py
import os

from flask import render_template, flash, redirect, url_for, current_app, \
    send_from_directory, request, abort, Blueprint, make_response
from syllaboard.utils import getTodayEntries
from flask_login import login_required, current_user
#from sqlalchemy.sql.expression import func

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        return render_template('main/index.html', entries=getTodayEntries())
    else:
        return render_template('main/index.html')


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/sw.js')
def service_worker():
    response = make_response(send_from_directory('static', 'sw.js'))
    response.headers['Cache-Control'] = 'no-cache'
    return response


@main_bp.route('/manifest.json')
def manifest():
    return send_from_directory('static', 'manifest.json')


@main_bp.route('/favicon.ico')
def favicon():
    return send_from_directory('static', 'favicon.ico')

syllaboard/blueprints/user.py
import os
from flask import render_template, flash, redirect, request, url_for, Blueprint, current_app
from flask_login import login_required, current_user

from syllaboard.components import db, avatars, csrf
from syllaboard.forms.user import UploadAvatarForm, CropAvatarForm
from syllaboard.models import Notification


user_bp = Blueprint('user', __name__)


@user_bp.route('/notification_token', methods=['POST'])
@login_required
@csrf.exempt
def notification_token():
    if request.is_json:
        data = request.json
        notification = Notification.query.filter_by(subscription_info=data).first()
        if not notification:
            if current_user.group:
                notification = Notification(group_id=current_user.group.id, subscription_info=data)
            else:
                notification = Notification(subscription_info=data)
            db.session.add(notification)
            db.session.commit()
    return 'ok'


@user_bp.route('/settings/avatar')
@login_required
def change_avatar():
    return render_template('settings/change_avatar.html')


@user_bp.route('/settings/avatar/upload', methods=['POST'])
@login_required
def upload_avatar():
    form = UploadAvatarForm()
    if form.validate_on_submit():
        image = form.image.data
        filename = avatars.save_avatar(image)
        if current_user.pfp_raw:
            os.remove(os.path.join(current_app.config['AVATARS_SAVE_PATH'], current_user.pfp_raw))
        current_user.pfp_raw = filename
        db.session.commit()
        flash('Image uploaded, please crop.', 'success')
    return redirect(url_for('.change_avatar'))


@user_bp.route('/settings/avatar/crop', methods=['POST'])
@login_required
def crop_avatar():
    form = CropAvatarForm()
    if form.validate_on_submit():
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        filenames = avatars.crop_avatar(current_user.pfp_raw, x, y, w, h)
        os.remove(os.path.join(current_app.config['AVATARS_SAVE_PATH'], current_user.pfp_s))
        os.remove(os.path.join(current_app.config['AVATARS_SAVE_PATH'], current_user.pfp_m))
        os.remove(os.path.join(current_app.config['AVATARS_SAVE_PATH'], current_user.pfp_l))
        current_user.pfp_s = filenames[0]
        current_user.pfp_m = filenames[1]
        current_user.pfp_l = filenames[2]
        db.session.commit()
        flash('Avatar updated.', 'success')
    return redirect(url_for('.change_avatar'))

syllaboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% block head %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>{% block title %}Home{% endblock title %}</title>
	<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="manifest" href="{{ url_for('static', filename='manifest.json') }}">
    <meta name="theme-color" content="#17171D" />
    <link rel="apple-touch-icon" href="{{ url_for('static', filename='images/icons/icon-128x128.png') }}" />
	{% endblock head %}
</head>
<body>
{% block nav %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Syllaboard</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
      <ul class="nav navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{{ url_for('main.index') }}">Home</a>
        </li>
    {% if current_user.is_authenticated %}
        <li class="dropdown nav-item">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown_user" data-bs-toggle="dropdown" aria-expanded="false">
                <img class="avatar-xs"
                     src="{{ url_for('main.get_avatar', filename=current_user.pfp_s) }}">
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown_user">
                <h6 class="dropdown-header">Logged in as {{ current_user.username }}</h6>
                <li><a class="dropdown-item" href="{{ url_for('main.index') }}">
                    <span class="oi oi-person"></span> My Home
                </a></li>
                <li><a class="dropdown-item" id="btnAdd"><span class="oi oi-box"> Install PWA app</a></li>
                <li><a class="dropdown-item" id="notify-btn"><span class="oi oi-box"> Notifications</a></li>
                <div class="dropdown-divider"></div>
                {% if current_user.is_headman %}
                <li><a class="dropdown-item" href="{{ url_for('dash.index') }}">
                    <span class="oi oi-dashboard"></span> Dashboard
                </a></li>
                {% endif %}
                <li><a class="dropdown-item" href="{{ url_for('user.change_avatar') }}">
                    <span class="oi oi-cog"></span> Settings
                </a></li>
                <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                    <span class="oi oi-power-standby"></span> Logout
                </a></li>
            </ul>
        </li>
    {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
        </li>
        <li><a class="nav-link" id="btnAdd">Install PWA</a></li>
    {% endif %}
      </ul>
    </div>
  </div>
</nav>

<nav class="breadcrumb fixed-bottom bg-dark" aria-label="breadcrumb" style="padding-left: 16px; margin-bottom: -10px;">
  <ol class="breadcrumb" style="padding-top: 4px;">
    {% if request.url_rule.endpoint != "main.index" %}<li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>{% endif %}
    {% block breadcrumbs %}{% endblock breadcrumbs %}
    <li class="breadcrumb-item active" aria-current="page">{{ self.title() }}</li>
  </ol>
</nav>
{% endblock nav %}

<main class="container">
	{% for message in get_flashed_messages(with_categories=True) %}
		<div class="alert alert-{{ message[0] }} alert-dismissible" role="alert">
			<button type="button" class="btn-close" data-bs-dismiss="alert"></button>
			{{ message[1] }}
		</div>
	{% endfor %}
	{% block content %}{% endblock content %}
	{% block footer %}
		<footer>
			<p class="float-left">
				<small> &copy; 2021 <a href="#" title="Written by Ilya_MZP">MZP</a>
				</small>
			</p>
			<p class="float-right">
				<small>

				</small>
			</p>
		</footer>
	{% endblock footer %}
</main>

{% block scripts %}
	<script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/app.js') }}"></script>
{% endblock %}
</body>
</html>