syllabin/blueprints/auth.py
from flask import render_template, flash, redirect, request, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login

from syllabin.components import db
from syllabin.forms.auth import LoginForm, RegisterForm
from syllabin.models import User, Group
from syllabin.utils import redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('Login success.', 'info')
                return redirect_back()
            else:
                flash('Your account is blocked.', 'warning')
                return redirect(url_for('main.index'))
        flash('Invalid username or password.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    registration_id = request.args.get('id', None)
    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        username = form.username.data
        password = form.password.data
        group_name = form.group.data
        if User.query.filter_by(username=username).first():
            flash('User exists.', 'warning')
            return redirect(url_for('.register'))
        registration_id = request.form['registration_id']
        if group_name:
            group = Group.query.filter_by(name=group_name).first()
            user = User(name=name, username=username, group_id=group.id)
        elif registration_id:
            template = User.query.filter_by(username=registration_id, active=False).first()
            user = User(name=name, group=template.group, username=username)
            user.set_role(template.role.name)
            db.session.delete(template)
        else:
            user = User(name=name, username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        flash('Account created.', 'info')
        return redirect(url_for('.login'))
    if form.errors:
        flash('Passwords do not match.', 'warning')
    if registration_id:
        return render_template('auth/register.html', form=form, registration_id=registration_id)
    else:
        groups = Group.query.all()
        return render_template('auth/register.html', form=form, groups=groups)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('main.index'))

syllabin/blueprints/main.py
import os
from datetime import date, timedelta
from flask import render_template, flash, redirect, url_for, current_app, send_from_directory, request, abort, Blueprint, make_response
from flask_login import login_required, current_user
from sqlalchemy import or_

from syllabin.utils import getDayEntries, getCurrentWeek, getFirstWeekDay, getMondayForWeek, getWeekEntries
from syllabin.models import Announcement
from syllabin.components import db

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    delta = request.args.get('delta', '0')
    if current_user.is_authenticated:
        today = date.today() + timedelta(days=int(delta))
        if current_user.group:
            announcements = Announcement.query.filter(or_(Announcement.group_id == current_user.group.id, Announcement.group_id == None)).all()
        else:
            announcements = Announcement.query.all()
        if announcements:
            for announcement in announcements:
                if announcement.expires.date() <= date.today():
                    db.session.delete(announcement)
                    db.session.commit()
        return render_template('main/index.html', announcements=announcements, entries=getDayEntries(today), week=getCurrentWeek(today), delta=int(delta))
    else:
        return render_template('main/index.html')


@main_bp.route('/week/<int:week_num>')
@login_required
def week(week_num):
    first_day = getMondayForWeek(week_num-1)
    range_string = first_day.strftime("%d/%m/%Y") + " to " + (first_day+timedelta(days=4)).strftime("%d/%m/%Y")
    colors = ["#C1A3A3", "#3F6DBD", "#43A126", "#B9BA30", "#B2508B"]
    return render_template('main/week.html', entries=getWeekEntries(week_num), week=week_num, colors=colors, range_string=range_string)


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/sw.js')
def service_worker():
    response = make_response(send_from_directory('static', 'sw.js'))
    response.headers['Cache-Control'] = 'no-cache'
    return response


@main_bp.route('/manifest.json')
def manifest():
    return send_from_directory('static', 'manifest.json')


@main_bp.route('/favicon.ico')
def favicon():
    return send_from_directory('static', 'favicon.ico')


@main_bp.route('/robots.txt')
def robots():
    return send_from_directory('static', 'robots.txt')

syllabin/blueprints/user.py
import os
from flask import render_template, flash, redirect, request, url_for, Blueprint, current_app
from flask_login import login_required, current_user

from syllabin.components import db, avatars, csrf
from syllabin.forms.user import UploadAvatarForm, CropAvatarForm, ChangePasswordForm
from syllabin.models import Subscription


user_bp = Blueprint('user', __name__)


@user_bp.route('/notification_token', methods=['POST'])
@login_required
@csrf.exempt
def notification_token():
    if request.is_json:
        data = request.json
        subscription = Subscription.query.filter_by(subscription_info=data).first()
        if not subscription:
            if current_user.group:
                subscription = Subscription(group_id=current_user.group.id, subscription_info=data)
            else:
                subscription = Subscription(subscription_info=data)
            db.session.add(subscription)
            db.session.commit()
    return '{ "status": "success" }'


@user_bp.route('/settings/avatar')
@login_required
def change_avatar():
    return render_template('settings/change_avatar.html')


@user_bp.route('/settings/avatar/upload', methods=['POST'])
@login_required
def upload_avatar():
    form = UploadAvatarForm()
    if form.validate_on_submit():
        image = form.image.data
        filename = avatars.save_avatar(image)
        if current_user.pfp_raw:
            os.remove(os.path.join(current_app.config['AVATARS_SAVE_PATH'], current_user.pfp_raw))
        current_user.pfp_raw = filename
        db.session.commit()
        flash('Image uploaded, please crop.', 'success')
    return redirect(url_for('.change_avatar'))


@user_bp.route('/settings/avatar/crop', methods=['POST'])
@login_required
def crop_avatar():
    form = CropAvatarForm()
    if form.validate_on_submit():
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        filenames = avatars.crop_avatar(current_user.pfp_raw, x, y, w, h)
        os.remove(os.path.join(current_app.config['AVATARS_SAVE_PATH'], current_user.pfp_s))
        os.remove(os.path.join(current_app.config['AVATARS_SAVE_PATH'], current_user.pfp_m))
        os.remove(os.path.join(current_app.config['AVATARS_SAVE_PATH'], current_user.pfp_l))
        current_user.pfp_s = filenames[0]
        current_user.pfp_m = filenames[1]
        current_user.pfp_l = filenames[2]
        db.session.commit()
        flash('Avatar updated.', 'success')
    return redirect(url_for('.change_avatar'))


@user_bp.route('/settings/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.validate_password(form.old_password.data):
            current_user.set_password(form.password.data)
            db.session.commit()
            flash('Password updated.', 'success')
            return redirect(url_for('.change_password', username=current_user.username))
        else:
            flash('Old password is incorrect.', 'warning')
    return render_template('settings/change_password.html', form=form)

syllabin/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% block head %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>{% block title %}Home{% endblock title %}</title>
	<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="manifest" href="{{ url_for('static', filename='manifest.json') }}">
    <meta name="theme-color" content="#17171D" />
    <link rel="apple-touch-icon" href="{{ url_for('static', filename='images/icons/icon-128x128.png') }}" />
	{% endblock head %}
</head>
<body>
<a id="skippy" style="position:absolute;width:1px;height:1px;padding:0;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0;" href="#content">
  <div class="container">
    <span class="skiplink-text">Skip to main content</span>
  </div>
</a>
{% block nav %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main.index') }}" aria-label="Syllabin"><img style="max-height: 54px; margin: -12px;" src="{{ url_for('static', filename='images/syllabin_logo_alt.svg') }}"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
      <ul class="nav navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{{ url_for('main.index') }}"><span class="oi oi-home" aria-hidden="true"></span> Home</a>
        </li>
        {% if current_user.is_headman %}
        <li class="nav-item active"><a class="nav-link" href="{{ url_for('dash.index') }}">
            <span class="oi oi-dashboard" aria-hidden="true"></span> Dashboard
        </a></li>
        {% endif %}
    {% if current_user.is_authenticated %}
        <li class="dropdown nav-item">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown_user" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Account actions">
                <img  aria-hidden="true"class="avatar-xs"
                     src="{{ url_for('main.get_avatar', filename=current_user.pfp_s) }}">
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown_user">
                <h6 class="dropdown-header">Logged in as {{ current_user.username }}</h6>
                <li><a class="dropdown-item" tabindex="0" id="btnAdd" aria-hidden="false" aria-label="Install PWA" aria-describedby="pwa_info">
                    <span class="oi oi-box" aria-hidden="true"></span> Install PWA app
                </a></li>
                <span id="pwa_info" style="display:none">Pressing the button will add this website to your phone as a web app for offline use.</span>
                <li><a class="dropdown-item" tabindex="0" id="notify-btn" aria-hidden="false" aria-label="Enable Notifications">
                    <span class="oi oi-bell" aria-hidden="true"></span> Notifications
                </a></li>
                <li><a class="dropdown-item" href="{{ url_for('user.change_password') }}">
                    <span class="oi oi-cog" aria-hidden="true"></span> Settings
                </a></li>
                <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                    <span class="oi oi-power-standby" aria-hidden="true"></span> Logout
                </a></li>
            </ul>
        </li>
    {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
        </li>
        <button id="btnAdd" aria-hidden="true" style="position:absolute;width:1px;height:1px;padding:0;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0;">Add to home screen</button>
        <button id="notify-btn" aria-hidden="true" style="position:absolute;width:1px;height:1px;padding:0;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0;">Enable notifications</button>
    {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% endblock nav %}

<main class="container">
	{% for message in get_flashed_messages(with_categories=True) %}
		<div class="alert alert-{{ message[0] }} alert-dismissible" role="alert">
			{{ message[1] }}
			<button type="button" class="btn-close" data-bs-dismiss="alert" tabindex="0" aria-label="Close"></button>
		</div>
	{% endfor %}
	{% block content %}{% endblock content %}
	{% block footer %}
		<footer>
			<p class="float-left">
				<small> &copy; 2021 <a href="#" title="Written by Ilya_MZP">MZP</a>
				</small>
			</p>
			<p class="float-right">
				<small>

				</small>
			</p>
		</footer>
	{% endblock footer %}
{% if request.url_rule.endpoint not in ["main.index", "main.tomorrow", "main.week"] %}
<nav class="breadcrumb fixed-bottom bg-dark" aria-label="breadcrumb" style="padding-left: 16px; margin-bottom: -10px;">
  <ol class="breadcrumb" style="padding-top: 4px;">
    {% if request.url_rule.endpoint != "main.index" %}<li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>{% endif %}
    {% block breadcrumbs %}{% endblock breadcrumbs %}
    <li class="breadcrumb-item active" aria-current="page">{{ self.title() }}</li>
  </ol>
</nav>
{% endif %}
</main>

{% block scripts %}
	<script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/app.js') }}"></script>
{% endblock %}
</body>
</html>

syllabin/templates/macros.html
{% macro render_breadcrumb(endpoint, title) %}
    <li class="breadcrumb-item"><a href="{{ url_for(endpoint, **kwargs) }}">{{ title }}</a></li>
{% endmacro %}