syllabin/blueprints/api.py
from flask import jsonify, Blueprint
from flask_login import login_required

from syllabin.components import db
from syllabin.models import User, Group, Subject, Room, Professor

api_bp = Blueprint('api', __name__)


@login_required
@api_bp.route('/roles', methods=['GET'])
def roles():
    role_names = []
    roles = Role.query.all()
    for role in roles:
        role_names.append(role.name)
    return jsonify(role_names)


@login_required
@api_bp.route('/subjects', methods=['GET'])
def subjects():
    sub_names = []
    subjects = Subject.query.all()
    for subject in subjects:
        sub_names.append(subject.name)
    return jsonify(sub_names)


@login_required
@api_bp.route('/professors', methods=['GET'])
def proffessors():
    prof_names = []
    proffessors = Professor.query.all()
    for proffessor in proffessors:
        prof_names.append(proffessor.name)
    return jsonify(prof_names)


@login_required
@api_bp.route('/rooms', methods=['GET'])
def rooms():
    room_names = []
    rooms = Room.query.all()
    for room in rooms:
        room_names.append(room.name)
    return jsonify(room_names)


@login_required
@api_bp.route('/groups', methods=['GET'])
def groups():
    group_names = []
    groups = Group.query.all()
    for group in groups:
        group_names.append(group.name)
    return jsonify(group_names)

syllabin/blueprints/dashboard.py
import datetime
from flask import render_template, flash, redirect, request, url_for, Blueprint
from flask_login import login_required, current_user
from flask_wtf import FlaskForm

from syllabin.components import db
from syllabin.models import Group, Subject, Room, Professor, Timetable, User
from syllabin.decorators import headman_required
from syllabin.utils import getCurrentWeek, getCurrentDay
from syllabin.notifications import notify_group

dash_bp = Blueprint('dash', __name__)


@dash_bp.route('')
@login_required
@headman_required
def index():
    groups = Group.query.all()
    rooms = Room.query.all()
    subjects = Subject.query.all()
    professors = Professor.query.all()
    if current_user.is_admin:
        timetable = Timetable.query.all()
    else:
        timetable = Timetable.query.filter_by(group_id=current_user.group.id).all()
    if current_user.is_admin:
        users = User.query.all()
    else:
        users = []
    return render_template('dashboard/index.html', users=users, groups=groups, rooms=rooms, subjects=subjects, timetable=timetable, professors=professors)


@dash_bp.route('/add_entry', methods=['GET', 'POST'])
@login_required
@headman_required
def add_entry():
    form = FlaskForm()
    if form.validate_on_submit():
        weeks = request.form.getlist('weeks[]')
        try:
            day = request.form['day']
        except:
            day = ""
        if not weeks:
            date_str = request.form['date']
            if date_str:
                weeks = [ str(getCurrentWeek(datetime.datetime.strptime(date_str, '%Y-%m-%d'))) ]
                day = getCurrentDay(datetime.datetime.strptime(date_str, '%Y-%m-%d'))
        lessons = request.form.getlist('lessons[]')
        subject = request.form['subject']
        room = request.form['room']
        professor = request.form['professor']
        try:
            group = request.form['group']
        except:
            group = current_user.group.name
        if all([weeks, lessons, day, subject, room, professor]):
            group_id = Group.query.filter_by(name=group).first()
            subject_id = Subject.query.filter_by(name=subject).first()
            room_id = Room.query.filter_by(name=room).first()
            professor_id = Professor.query.filter_by(name=professor).first()
            if not group_id:
                group_id = Group.query.filter_by(name=group).first()
                flash('No such group. Create a new group first.', 'warning')
                return redirect(url_for('dash.add_entry'))  # TODO: Redirect to create group page
            if not professor_id:
                professor_id = Professor(name=professor)
                db.session.add(professor_id)
            if not room_id:
                room_id = Room(name=room)
                db.session.add(room_id)
            if not subject_id:
                subject_id = Subject(name=subject)
                db.session.add(subject_id)
            db.session.commit()
            entry = Timetable(weekday=day, week_nums=weeks, lesson_nums=lessons, room_id=room_id.id, subj_id=subject_id.id, group_id=group_id.id, prof_id=professor_id.id)
            db.session.add(entry)
            db.session.commit()
            flash('Success.', 'info')
        else:
            flash('Some fields were empty.', 'warning')
        return redirect(url_for('dash.add_entry'))
    return render_template('dashboard/add_entry.html', form=form, groups=Group.query.all())


@dash_bp.route('/edit_entry/<int:entry_id>', methods=['GET', 'POST'])
@login_required
@headman_required
def edit_entry(entry_id):
    form = FlaskForm()
    entry = Timetable.query.get(entry_id)
    if entry is None:
        flash('Entry does not exixt.', 'warning')
        return redirect(url_for('dash.index'))
    if form.validate_on_submit():
        weeks = request.form.getlist('weeks[]')
        lessons = request.form.getlist('lessons[]')
        subject = request.form['subject']
        room = request.form['room']
        day = request.form['day']
        professor = request.form['professor']
        group = request.form.get('group', current_user.group.name)
        if all([weeks, lessons, day, subject, room, professor, group]):
            group_id = Group.query.filter_by(name=group).first()
            if group_id is None:
                flash("Group doesn't exist.", 'warning')
                return redirect(url_for('dash.edit_entry', entry_id=entry_id))
            subject_id = Subject.query.filter_by(name=subject).first()
            room_id = Room.query.filter_by(name=room).first()
            professor_id = Professor.query.filter_by(name=professor).first()
            if not professor_id:
                professor_id = Professor(name=professor)
                db.session.add(professor_id)
            if not room_id:
                room_id = Room(name=room)
                db.session.add(room_id)
            if not subject_id:
                subject_id = Subject(name=subject)
                db.session.add(subject_id)
            try:
                db.session.commit()
            except:
                db.session.rollback()
                flash('Unknown error.', 'warning')
                pass
            entry.prof_id = professor_id.id
            entry.subj_id = subject_id.id
            entry.group_id = group_id.id
            entry.room_id = room_id.id
            entry.lesson_nums = lessons
            entry.week_nums = weeks
            entry.weekday = day
            try:
                db.session.commit()
                flash('Success.', 'info')
                return redirect(url_for('dash.manage_entries'))
            except:
                db.session.rollback()
                flash('Unknown error.', 'warning')
                pass
    return render_template('dashboard/edit_entry.html', form=form, entry=entry, groups=Group.query.all())


@dash_bp.route('/manage_entries')
@login_required
@headman_required
def manage_entries():
    if current_user.is_admin:
        entries = Timetable.query.all()
    else:
        entries = Timetable.query.filter_by(group_id=current_user.group.id).all()
    return render_template('dashboard/manage_entries.html', entries=entries)


@dash_bp.route('/delete_entry/<int:entry_id>')
@login_required
def delete_entry(entry_id):
    to_delete = Timetable.query.get(entry_id)
    if to_delete:
        db.session.delete(to_delete)
        db.session.commit()
        flash('Success.', 'info')
    return redirect(url_for('dash.manage_entries'))


@dash_bp.route('/manage_subjects')
@login_required
@headman_required
def manage_subjects():
    subjects = Subject.query.all()
    return render_template('dashboard/manage_subjects.html', subjects=subjects)


@dash_bp.route('/delete_subject/<int:subject_id>')
@login_required
@headman_required
def delete_subject(subject_id):
    if not current_user.is_admin:
        used = Timetable.query.filter(Timetable.subj_id==subject_id, Timetable.group_id != current_user.group.id).first()
        if used:
            flash('This item is used by another group and cannot be deleted.', 'danger')
            return redirect(url_for('dash.manage_subjects'))
    to_delete = Subject.query.get(subject_id)
    if to_delete:
        db.session.delete(to_delete)
        db.session.commit()
        flash('Success.', 'info')
    return redirect(url_for('dash.manage_subjects'))


@dash_bp.route('/edit_subject/<int:subject_id>', methods=['GET', 'POST'])
@login_required
@headman_required
def edit_subject(subject_id):
    form = FlaskForm()
    to_edit = Subject.query.get(subject_id)
    if form.validate_on_submit():
        subject_name = request.form['subject']
        if not subject_name:
            flash('Name cannot be empty.', 'warning')
            return redirect(url_for('dash.manage_subjects'))
        if not current_user.is_admin:
            used = Timetable.query.filter(Timetable.subj_id==subject_id, Timetable.group_id!=current_user.group.id).first()
            if used:
                flash('This item is used by another group and cannot be edited.', 'danger')
                return redirect(url_for('dash.manage_subjects'))
        subject_id = Subject.query.filter_by(name=subject_name).first()
        if not subject_id:
            to_edit.name = subject_name
            db.session.commit()
        flash('Success.', 'info')
        return redirect(url_for('dash.manage_subjects'))
    return render_template('dashboard/edit_subject.html', form=form, subject=to_edit)


@dash_bp.route('/manage_professors')
@login_required
@headman_required
def manage_professors():
    professors = Professor.query.all()
    return render_template('dashboard/manage_professors.html', professors=professors)


@dash_bp.route('/delete_professor/<int:professor_id>')
@login_required
@headman_required
def delete_professor(professor_id):
    if not current_user.is_admin:
        used = Timetable.query.filter(Timetable.prof_id==professor_id, Timetable.group_id!=current_user.group.id).first()
        if used:
            flash('This item is used by another group and cannot be deleted.', 'danger')
            return redirect(url_for('dash.manage_professors'))
    to_delete = Professor.query.get(professor_id)
    if to_delete:
        db.session.delete(to_delete)
        db.session.commit()
        flash('Success.', 'info')
    return redirect(url_for('dash.manage_professors'))


@dash_bp.route('/edit_professor/<int:professor_id>', methods=['GET', 'POST'])
@login_required
@headman_required
def edit_professor(professor_id):
    form = FlaskForm()
    to_edit = Professor.query.get(professor_id)
    if form.validate_on_submit():
        professor_name = request.form['professor']
        if not professor_name:
            flash('Name cannot be empty.', 'warning')
            return redirect(url_for('dash.manage_professors'))
        if not current_user.is_admin:

syllabin/templates/dashboard/add_entry.html
{% extends 'base.html' %}
{% from 'macros.html' import render_breadcrumb %}

{% block title %}Add Entry{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/select2.min.css') }}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='css/autocomplete.css') }}" rel="stylesheet" />
{% endblock %}
{% block content %}
    <div class="jumbotron">
        <div class="row" id="content">
            <div class="col-md-8">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header"><h4>Add entry to the timetable</h4></div>
                    <div class="card-body">

<form autocomplete="off" action="{{ url_for('dash.add_entry') }}" method="POST">
{{ form.csrf_token }}
<div class="form-group">
{% if current_user.is_admin %}
    <label for="group_input">Select group</label>
    <select id="group_input" class="form-control" name="group">
{% if groups %}
      {% for key in groups %}
      <option>{{ key.name }}</option>
      {% endfor %}
{% else %}
      <option>Create a group before adding entries</option>
{% endif %}
    </select>
{% endif %}
    <div class="autocomplete mt-1">
        <input id="subj_inp" type="text" name="subject" placeholder="Subject">
    </div>
    <div class="autocomplete">
        <input id="prof_inp" type="text" name="professor" placeholder="Professor">
    </div>
    <div class="autocomplete">
        <input id="room_inp" type="text" name="room" placeholder="Room">
    </div>

    <div class="form-group form-inline mb-1">
    <label for="weeks_input">Lesson numbers</label>
    <select id="lessons_input" name="lessons[]" multiple="multiple" style="width:100%">
      <option value="1">1 (9:00-10:20)</option>
      <option value="2">2 (10:30-11:50)</option>
      <option value="3">3 (12:40-14:00)</option>
      <option value="4">4 (14:10-15:30)</option>
      <option value="5">5 (15:40-17:00)</option>
    </select>
    </div>

    <div class="form-group form-inline mb-1">
    <label for="weeks_input">Week numbers (when lesson occurs)</label>
    <select id="weeks_input" class="form-control" name="weeks[]" multiple="multiple">
      {% for week in range(1,20) %}
      <option>{{ week }}</option>
      {% endfor %}
    </select>
    <button class="btn btn-outline-secondary mt-1" type="button" id="dateinput_btn">Date Input</button>
    </div>

    <label for="day_input">Day of the week</label>
    <select id="day_input" class="form-control" name="day">
      {% for key in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %}
      <option>{{ key }}</option>
      {% endfor %}
    </select>
  </div>
  <input type="submit" class="mt-3" value="Add entry">
</form>

</div>
</div>
</div>
</div>
</div>
</div>

{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/autocomplete.js') }}"></script>
    <script src="{{ url_for('static', filename='js/select2.min.js') }}"></script>
    <script>
    autocomplete(document.getElementById("subj_inp"), "{{ url_for('api.subjects') }}");
    autocomplete(document.getElementById("prof_inp"), "{{ url_for('api.proffessors') }}");
    autocomplete(document.getElementById("room_inp"), "{{ url_for('api.rooms') }}");
    $('#day_input').select2();
    $('#weeks_input').select2();
    $('#lessons_input').select2();
    $('#group_input').select2();
    $('#dateinput_btn').click(function() {
        $('#weeks_input').select2('destroy');
        $('#day_input').select2('destroy');
        $('#day_input').remove();
        $('#weeks_input').replaceWith('<br><input type="date" id="weeks_input" name="date">');
        $('#dateinput_btn').remove();
        $('label[for="day_input"]').remove();
    });
    </script>
{% endblock %}
{% block breadcrumbs %}
{{ render_breadcrumb('dash.index', "Dashboard") }}
{% endblock breadcrumbs %}

syllabin/templates/dashboard/edit_entry.html
{% extends 'base.html' %}
{% from 'macros.html' import render_breadcrumb %}

{% block title %}Edit Entry{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/select2.min.css') }}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='css/autocomplete.css') }}" rel="stylesheet" />
{% endblock %}
{% block content %}
    <div class="jumbotron">
        <div class="row" id="content">
            <div class="col-md-8">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header"><h4>Edit timetable entry</h4></div>
                    <div class="card-body">

<form autocomplete="off" action="{{ url_for('dash.edit_entry', entry_id=entry.id) }}" method="POST">
{{ form.csrf_token }}
<div class="form-group">
    <label for="group_input">Select group</label>
    <select id="group_input" class="form-control" name="group">
    {% for key in groups %}
      <option>{{ key.name }}</option>
    {% endfor %}
    </select>
    <div class="autocomplete" style="margin-top: 4px;">
        <input id="subj_inp" type="text" name="subject" placeholder="Subject" value="{{ entry.subject.name }}">
    </div>
    <div class="autocomplete">
        <input id="prof_inp" type="text" name="professor" placeholder="Professor" value="{{ entry.professor.name }}">
    </div>
    <div class="autocomplete">
        <input id="room_inp" type="text" name="room" placeholder="Room" value="{{ entry.room.name }}">
    </div>

    <div class="form-group form-inline" style="margin-bottom:4px">
    <label for="weeks_input">Lesson numbers</label>
    <select id="lessons_input" name="lessons[]" multiple="multiple" style="width:100%">
      <option value="1">1 (9:00-10:20)</option>
      <option value="2">2 (10:30-11:50)</option>
      <option value="3">3 (12:40-14:00)</option>
      <option value="4">4 (14:10-15:30)</option>
      <option value="5">5 (15:40-17:00)</option>
    </select>
    </div>

    <div class="form-group form-inline" style="margin-bottom:4px">
    <label for="weeks_input">Week numbers (when lesson occurs)</label>
    <select id="weeks_input" class="form-control" name="weeks[]" multiple="multiple">
      {% for week in range(1,20) %}
      <option>{{ week }}</option>
      {% endfor %}
    </select>
    </div>
    <label for="day_input">Day of the week</label>
    <select id="day_input" class="form-control" name="day">
      {% for key in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %}
      <option>{{ key }}</option>
      {% endfor %}
    </select>
  </div>
  <input type="submit"  style="margin-top:8px" value="Apply changes">
</form>

</div>
</div>
</div>
</div>
</div>
</div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/autocomplete.js') }}"></script>
    <script src="{{ url_for('static', filename='js/select2.min.js') }}"></script>
    <script>
    autocomplete(document.getElementById("subj_inp"), "{{ url_for('api.subjects') }}");
    autocomplete(document.getElementById("prof_inp"), "{{ url_for('api.proffessors') }}");
    autocomplete(document.getElementById("room_inp"), "{{ url_for('api.rooms') }}");
    $('#day_input').select2();
    $('#weeks_input').select2();
    $('#lessons_input').select2();
    $('#group_input').select2();

    var weeks = "{{ ','.join(entry.week_nums) }}".split(',');
    var lessons = "{{ ','.join(entry.lesson_nums) }}".split(',');
    $('#lessons_input').val(lessons);
    $('#lessons_input').trigger('change');
    $('#weeks_input').val(weeks);
    $('#weeks_input').trigger('change');
    $('#day_input').val("{{ entry.weekday }}");
    $('#day_input').trigger('change');
    $('#group_input').val("{{ entry.group.name }}");
    $('#group_input').trigger('change');
    </script>
{% endblock %}
{% block breadcrumbs %}
{{ render_breadcrumb('dash.index', "Dashboard") }}
{% endblock breadcrumbs %}

syllabin/templates/dashboard/edit_professor.html
{% extends 'base.html' %}
{% from 'macros.html' import render_breadcrumb %}

{% block title %}Edit Professor{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/autocomplete.css') }}" rel="stylesheet" />
{% endblock %}
{% block content %}
    <div class="jumbotron">
        <div class="row" id="content">
            <div class="col-md-8">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header"><h4>Edit professor name</h4></div>
                    <div class="card-body">

<form autocomplete="off" action="{{ url_for('dash.edit_professor', professor_id=professor.id) }}" method="POST">
{{ form.csrf_token }}
<div class="form-group">
    <div class="autocomplete">
        <input id="prof_inp" type="text" name="professor" placeholder="Professor" value="{{ professor.name }}">
    </div>
  </div>
  <input type="submit"  style="margin-top:4px" value="Apply changes">
</form>

</div>
</div>
</div>
</div>
</div>
</div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/autocomplete.js') }}"></script>
    <script>
    autocomplete(document.getElementById("prof_inp"), "{{ url_for('api.proffessors') }}");
    </script>
{% endblock %}
{% block breadcrumbs %}
{{ render_breadcrumb('dash.index', "Dashboard") }}
{% endblock breadcrumbs %}

syllabin/templates/dashboard/edit_room.html
{% extends 'base.html' %}
{% from 'macros.html' import render_breadcrumb %}

{% block title %}Edit Room{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/autocomplete.css') }}" rel="stylesheet" />
{% endblock %}
{% block content %}
    <div class="jumbotron">
        <div class="row" id="content">
            <div class="col-md-8">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header"><h4>Edit room name</h4></div>
                    <div class="card-body">

<form autocomplete="off" action="{{ url_for('dash.edit_room', room_id=room.id) }}" method="POST">
{{ form.csrf_token }}
<div class="form-group">
    <div class="autocomplete">
        <input id="room_inp" type="text" name="room" placeholder="Room" value="{{ room.name }}">
    </div>
  </div>
  <input type="submit"  style="margin-top:4px" value="Apply changes">
</form>

</div>
</div>
</div>
</div>
</div>
</div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/autocomplete.js') }}"></script>
    <script>
    autocomplete(document.getElementById("room_inp"), "{{ url_for('api.rooms') }}");
    </script>
{% endblock %}
{% block breadcrumbs %}
{{ render_breadcrumb('dash.index', "Dashboard") }}
{% endblock breadcrumbs %}

syllabin/templates/dashboard/edit_subject.html
{% extends 'base.html' %}
{% from 'macros.html' import render_breadcrumb %}

{% block title %}Eidt Subject{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/autocomplete.css') }}" rel="stylesheet" />
{% endblock %}
{% block content %}
    <div class="jumbotron">
        <div class="row" id="content">
            <div class="col-md-8">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header"><h4>Edit subject name</h4></div>
                    <div class="card-body">

<form autocomplete="off" action="{{ url_for('dash.edit_subject', subject_id=subject.id) }}" method="POST">
{{ form.csrf_token }}
<div class="form-group">
    <div class="autocomplete">
        <input id="subject_inp" type="text" name="subject" placeholder="Subject" value="{{ subject.name }}">
    </div>
  </div>
  <input type="submit"  style="margin-top:4px" value="Apply changes">
</form>

</div>
</div>
</div>
</div>
</div>
</div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/autocomplete.js') }}"></script>
    <script>
    autocomplete(document.getElementById("subject_inp"), "{{ url_for('api.subjects') }}");
    </script>
{% endblock %}
{% block breadcrumbs %}
{{ render_breadcrumb('dash.index', "Dashboard") }}
{% endblock breadcrumbs %}

syllabin/templates/dashboard/manage_professors.html
{% extends 'base.html' %}
{% from 'macros.html' import render_breadcrumb %}
{% block title %}Manage Professors{% endblock %}

{% block content %}
	<div class="page-header" style="padding-top:0">
		<h1 style="margin:0">Manage professors</h1>
	</div>
	<div class="row" id="content">
		<div class="col-sm-16">
  <input class="form-control mt-2 mb-2" id="searchInput" type="text" placeholder="Search..">
{% if professors %}
<div class="card">
  <ul id="professorList" class="list-group list-group-flush">
{% for professor in professors %}
    <li class="list-group-item">
{{ professor.name }}
<br>
    <div class="btn-group float-end">
        <a type="button" href="{{ url_for('dash.edit_professor', professor_id=professor.id) }}" class="btn btn-outline-primary">Edit</a>
        <button type="button" data-uri="{{ url_for('dash.delete_professor', professor_id=professor.id) }}" class="btn btn-outline-danger delete-btn">Delete</button>
    </div>
    </li>
{% endfor %}
  </ul>
</div>
{% endif %}
		</div>
	</div>
<div class="modal fade" id="deleteProfessorDialog" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
      </div>
      <div class="modal-body">
        This will delete the professor and all timetable entries that reference them.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <a type="button" id="delete_btn" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block scripts %}
    {{ super() }}
<script>
$(document).ready(function(){
  $(".delete-btn").click(function() {
    var link = $(this).data('uri');
    console.log(link);
    $(".modal-footer #delete_btn").attr("href", link );
    $("#deleteProfessorDialog").modal("show");
  });
  $("#searchInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#professorList li").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
{% endblock %}
{% block breadcrumbs %}
{{ render_breadcrumb('dash.index', "Dashboard") }}
{% endblock breadcrumbs %}

syllabin/templates/dashboard/manage_subjects.html
{% extends 'base.html' %}
{% from 'macros.html' import render_breadcrumb %}
{% block title %}Manage Subjects{% endblock %}

{% block content %}
	<div class="page-header" style="padding-top:0">
		<h1 style="margin:0">Manage subjects</h1>
	</div>
	<div class="row" id="content">
		<div class="col-sm-16">
  <input class="form-control mt-2 mb-2" id="searchInput" type="text" placeholder="Search..">
{% if subjects %}
<div class="card">
  <ul id="subjectList" class="list-group list-group-flush">
{% for subject in subjects %}
    <li class="list-group-item">
{{ subject.name }}
<br>
    <div class="btn-group float-end">
        <a type="button" href="{{ url_for('dash.edit_subject', subject_id=subject.id) }}" class="btn btn-outline-primary">Edit</a>
        <button type="button" data-uri="{{ url_for('dash.delete_subject', subject_id=subject.id) }}" class="btn btn-outline-danger delete-btn">Delete</button>
    </div>
    </li>
{% endfor %}
  </ul>
</div>
{% endif %}
		</div>
	</div>
<div class="modal fade" id="deleteSubjectDialog" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
      </div>
      <div class="modal-body">
        This will delete the subject and all timetable entries that reference it.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <a type="button" id="delete_btn" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block scripts %}
    {{ super() }}
<script>
$(document).ready(function(){
  $(".delete-btn").click(function() {
    var link = $(this).data('uri');
    console.log(link);
    $(".modal-footer #delete_btn").attr("href", link );
    $("#deleteSubjectDialog").modal("show");
  });
  $("#searchInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#subjectList li").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
{% endblock %}
{% block breadcrumbs %}
{{ render_breadcrumb('dash.index', "Dashboard") }}
{% endblock breadcrumbs %}